export { default } from "next-auth/middleware";

export const config = {
  //   matcher: [
  //     "/admin",
  //     "/admin/aspirasi",
  //     "/admin/beranda",
  //     "/admin/galeri",
  //     "/admin/galeri/photo",
  //     "/admin/galeri/photo/add",
  //     "/admin/galeri/photo/([a-zA-Z0-9-_]+)",
  //     "/admin/galeri/video",
  //     "/admin/galeri/video/add",
  //     "/admin/galeri/video/([a-zA-Z0-9-_]+)",
  //     "/admin/komunitas",
  //     "/admin/narasi",
  //     "/admin/narasi/add",
  //     "/admin/narasi/([a-zA-Z0-9-_]+)",
  //     "/admin/pencapaian",
  //     "/admin/pencapaian/book",
  //     "/admin/pencapaian/book/add",
  //     "/admin/pencapaian/book/([a-zA-Z0-9-_]+)",
  //     "/admin/pencapaian/ilmiah",
  //     "/admin/pencapaian/ilmiah/add",
  //     "/admin/pencapaian/ilmiah/([a-zA-Z0-9-_]+)",
  //     "/admin/pencapaian/penghargaan",
  //     "/admin/pencapaian/penghargaan/add",
  //     "/admin/pencapaian/penghargaan/([a-zA-Z0-9-_]+)",
  //     "/admin/riwayat",
  //     "/admin/riwayat/organisasi",
  //     "/admin/riwayat/organisasi/add",
  //     "/admin/riwayat/organisasi/([a-zA-Z0-9-_]+)",
  //     "/admin/riwayat/pekerjaan",
  //     "/admin/riwayat/pekerjaan/add",
  //     "/admin/riwayat/pekerjaan/([a-zA-Z0-9-_]+)",
  //     "/admin/riwayat/pendidikan",
  //     "/admin/riwayat/pendidikan/add",
  //     "/admin/riwayat/pendidikan/([a-zA-Z0-9-_]+)",
  //     "/admin/tentang",
  //   ],
  matcher: ["/admin/:path*"],
};
